spring.application.name=Leave_and_Attendance_Management_System
spring.datasource.url=jdbc:mysql://localhost:3306/LAMS_db
spring.datasource.username=root
spring.datasource.password=dronadhula

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=8080
